// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoomSah2YafQo0BU3XcC2TU0ahQs1-V2Q',
    appId: '1:1461254704:web:200529647c48716fbb0bf5',
    messagingSenderId: '1461254704',
    projectId: 'login-ba9c1',
    authDomain: 'login-ba9c1.firebaseapp.com',
    storageBucket: 'login-ba9c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYtjVmYspn0Zl7Z2LG49Rmz1K3BHaexsA',
    appId: '1:1461254704:android:83ea397aeae0717cbb0bf5',
    messagingSenderId: '1461254704',
    projectId: 'login-ba9c1',
    storageBucket: 'login-ba9c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyColn8E25e9KhU1v3hLhLHVQrGtXClBWUU',
    appId: '1:1461254704:ios:7a351a67833de417bb0bf5',
    messagingSenderId: '1461254704',
    projectId: 'login-ba9c1',
    storageBucket: 'login-ba9c1.appspot.com',
    iosBundleId: 'com.example.login',
  );
}
